added molecule entity type and updated references
dynotx/liminal-orm pull request #70
Opened 2024-12-04 23:26 UTC by aarushgarg1110

2024-12-06 13:19 UTC, ndamania00 requested changes
Looks good. Can you update the mappers in generate_files.py? To connect BenchlingEntityType to mixin and subdirectory

2024-12-06 21:05 UTC, aarushgarg1110 commented
In that specific file, It looks like i added the molecule entity to those parts. I can't seem to find any other line where I didn't connect it

2024-12-06 21:07 UTC, ndamania00 approved these changes
missed that, let's merge! 🚀

2024-12-07 20:39 UTC, ndamania00 approved these changes

2024-12-07 20:48 UTC, merged